version: "3.8"
services:
  mysql_HrentDb:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=HrentDb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3310:3306
  pma_HrentDb:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8087:80
    links:
      - mysql_HrentDb:mysql_HrentDb
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_HrentDb